services:
  trading_bot:
    build: .
    environment:
      - ENV=dev
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_TRADING_BOT}
      - INFISICAL_API_URL=https://infisical.datawarp.dev
      - INFISICAL_PROJECT_ID=c33e9242-33ba-4f8c-8f0b-3c58ddb7e2f5
    volumes:
      - trading_logs:/app/logs
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - logs/
        - action: rebuild
          path: ./pyproject.toml

volumes:
  trading_logs: